[project]
channels = [
  "https://prefix.dev/rapidsai",
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/meta-forge",
  "conda-forge",
]
name = "LightSeq"
platforms = ["linux-64"]
preview = ["pixi-build"]
version = "0.0.1"
[system-requirements]
cuda = "12.7"

[tasks]

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"

[dependencies]
cuda = "12.6.*"
pytorch = { version = ">=2.7.0", build = "*cuda*" }
python = "3.10.*"
pip = "*"
pandas = ">=2.2.3,<3"
absl-py = ">=2.2.0,<3"
tqdm = ">=4.67.1,<5"
flash-attn-3 = ">=2025.5.19,<2026"
flash-attn = ">=2.7.4.post1,<3"
transformers = ">=4.52.4,<5"

[feature.dev.dependencies]
pytest = "*"
pre-commit = ">=4.2.0,<5"
ruff = ">=0.11.2,<0.12"

[feature.dev.pypi-dependencies]
lightseq = { path = ".", editable = true }

[environments]
dev = { features = ["dev"], solve-group = "default" }
